---
- name: Remove script output directory
  ansible.builtin.file:
    path: "{{ lab_scripts_output_dir }}"
    state: absent

- name: Display removal message
  ansible.builtin.debug:
    msg: "RHTPA scripts directory removed: {{ lab_scripts_output_dir }}"
