---
- name: Remove script output directory
  ansible.builtin.file:
    path: "{{ rhpds_build_secured_dev_workflows_lab_scripts_output_dir }}"
    state: absent

- name: Display removal message
  ansible.builtin.debug:
    msg: "RHTPA scripts directory removed: {{ rhpds_build_secured_dev_workflows_lab_scripts_output_dir }}"
