---
# Namespace configuration
lab_scripts_tpa_namespace: trusted-profile-analyzer
lab_scripts_tas_namespace: tssc-tas
lab_scripts_keycloak_namespace: sso
lab_scripts_pipelines_namespace: openshift-pipelines
lab_scripts_app_ci_namespace: tssc-app-ci

# Script output directory
lab_scripts_output_dir: ~/lab-assets

# Module 1: TPA Configuration
lab_scripts_tpa_keycloak_realm: tpa
lab_scripts_tpa_admin_username: "tpa-admin"
lab_scripts_tpa_admin_password: "openshift"
lab_scripts_tpa_cli_client_secret: "5460cc91-4e20-4edd-881c-b15b169f8a79"

# SBOM configuration
lab_scripts_tpa_example_sbom_path: ~/lab-assets/example-sbom.json
lab_scripts_tpa_sbom_id: test-sbom

# Module 2: TAS Configuration
lab_scripts_tas_chains_realm: tas-chains
lab_scripts_tas_sso_realm: sso
lab_scripts_tas_client_id: trusted-artifact-signer
